
package edu.up.bsi.conv.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Login", targetNamespace = "http://soap.conv.bsi.up.edu/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Login {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.conv.bsi.up.edu/Login/getMessageLoginRequest", output = "http://soap.conv.bsi.up.edu/Login/getMessageLoginResponse")
    public String getMessageLogin();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.conv.bsi.up.edu/Login/getTelefoneRequest", output = "http://soap.conv.bsi.up.edu/Login/getTelefoneResponse")
    public String getTelefone(
        @WebParam(name = "arg0", partName = "arg0")
        Usuario arg0);

    /**
     * 
     * @return
     *     returns edu.up.bsi.conv.soap.ListaUsuarios
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.conv.bsi.up.edu/Login/getAllRequest", output = "http://soap.conv.bsi.up.edu/Login/getAllResponse")
    public ListaUsuarios getAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.conv.bsi.up.edu/Login/getIdadeRequest", output = "http://soap.conv.bsi.up.edu/Login/getIdadeResponse")
    public int getIdade(
        @WebParam(name = "arg0", partName = "arg0")
        Usuario arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.conv.bsi.up.edu/Login/getCpfRequest", output = "http://soap.conv.bsi.up.edu/Login/getCpfResponse")
    public String getCpf(
        @WebParam(name = "arg0", partName = "arg0")
        Usuario arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.up.bsi.conv.soap.Usuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.conv.bsi.up.edu/Login/getTodosOsDadosRequest", output = "http://soap.conv.bsi.up.edu/Login/getTodosOsDadosResponse")
    public Usuario getTodosOsDados(
        @WebParam(name = "arg0", partName = "arg0")
        Usuario arg0);

}
