
package edu.up.bsi.conv.fib.soap.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FibonacciService", targetNamespace = "http://server.soap.fib.conv.bsi.up.edu/", wsdlLocation = "http://localhost:8080/fibonacci?wsdl")
public class FibonacciService
    extends Service
{

    private final static URL FIBONACCISERVICE_WSDL_LOCATION;
    private final static WebServiceException FIBONACCISERVICE_EXCEPTION;
    private final static QName FIBONACCISERVICE_QNAME = new QName("http://server.soap.fib.conv.bsi.up.edu/", "FibonacciService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/fibonacci?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FIBONACCISERVICE_WSDL_LOCATION = url;
        FIBONACCISERVICE_EXCEPTION = e;
    }

    public FibonacciService() {
        super(__getWsdlLocation(), FIBONACCISERVICE_QNAME);
    }

    public FibonacciService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FIBONACCISERVICE_QNAME, features);
    }

    public FibonacciService(URL wsdlLocation) {
        super(wsdlLocation, FIBONACCISERVICE_QNAME);
    }

    public FibonacciService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FIBONACCISERVICE_QNAME, features);
    }

    public FibonacciService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FibonacciService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Fibonacci
     */
    @WebEndpoint(name = "FibonacciPort")
    public Fibonacci getFibonacciPort() {
        return super.getPort(new QName("http://server.soap.fib.conv.bsi.up.edu/", "FibonacciPort"), Fibonacci.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Fibonacci
     */
    @WebEndpoint(name = "FibonacciPort")
    public Fibonacci getFibonacciPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.soap.fib.conv.bsi.up.edu/", "FibonacciPort"), Fibonacci.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FIBONACCISERVICE_EXCEPTION!= null) {
            throw FIBONACCISERVICE_EXCEPTION;
        }
        return FIBONACCISERVICE_WSDL_LOCATION;
    }

}
