
package edu.up.bsi.conv.fib.soap.server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Fibonacci", targetNamespace = "http://server.soap.fib.conv.bsi.up.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Fibonacci {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fibonacci", targetNamespace = "http://server.soap.fib.conv.bsi.up.edu/", className = "edu.up.bsi.conv.fib.soap.server.Fibonacci_Type")
    @ResponseWrapper(localName = "fibonacciResponse", targetNamespace = "http://server.soap.fib.conv.bsi.up.edu/", className = "edu.up.bsi.conv.fib.soap.server.FibonacciResponse")
    @Action(input = "http://server.soap.fib.conv.bsi.up.edu/Fibonacci/fibonacciRequest", output = "http://server.soap.fib.conv.bsi.up.edu/Fibonacci/fibonacciResponse")
    public List<Integer> fibonacci(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "soma", targetNamespace = "http://server.soap.fib.conv.bsi.up.edu/", className = "edu.up.bsi.conv.fib.soap.server.Soma")
    @ResponseWrapper(localName = "somaResponse", targetNamespace = "http://server.soap.fib.conv.bsi.up.edu/", className = "edu.up.bsi.conv.fib.soap.server.SomaResponse")
    @Action(input = "http://server.soap.fib.conv.bsi.up.edu/Fibonacci/somaRequest", output = "http://server.soap.fib.conv.bsi.up.edu/Fibonacci/somaResponse")
    public int soma(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fibonacci2", targetNamespace = "http://server.soap.fib.conv.bsi.up.edu/", className = "edu.up.bsi.conv.fib.soap.server.Fibonacci2")
    @ResponseWrapper(localName = "fibonacci2Response", targetNamespace = "http://server.soap.fib.conv.bsi.up.edu/", className = "edu.up.bsi.conv.fib.soap.server.Fibonacci2Response")
    @Action(input = "http://server.soap.fib.conv.bsi.up.edu/Fibonacci/fibonacci2Request", output = "http://server.soap.fib.conv.bsi.up.edu/Fibonacci/fibonacci2Response")
    public List<Integer> fibonacci2(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
